### ISSUE TITLE
Application is not working

### ISSUE THREAD

**Issue by hemandroid** [daemon369/android-screen-recorder#1]
Either screenshot or the Screen recorder feature is not working. This example is still incomplete. It doesn't have the manifest or even runtime permission for accessing the external storage to store the data.

**Comment by daemon369** [comment]
Yes, it's incomplete yet. But it's working. Screen recorder save video to /sdcard/Android/data/me.daemon.screenrecorder.demo/files/video.mp4 for now and i will refactor it later. Screenshot not save image right now, and i will save images later. As for external storage permissions, you don't need these any more, just save media file by MediaStore, just check my [storage repo](https://github.com/daemon369/android-storage)

**Comment by daemon369** [comment]
I pushed some commits. Video file is saved through MediaStore and a toast is showing to notify video file uri; image data is pass to imageCallback and related logs are printed; you can save a single screenshot and close the ScreenShot instance, or you can get lots of screenshots and do other actions, such as combining multiple screenshots to generate a long image as the screen scrolls

**Comment by daemon369** [comment]
Issue is fixed somehow, i will optimze it after
